name: Pythonlint

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  python-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "dpugen"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: true
          extra-isort-options: "--line-length 160 --wrap-length 80 --multi-line 3 --project dpugen --project dashgen --project saigen --force-grid-wrap 2"
  python-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "dpugen"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-flake8-options: "--max-line-length 160"